%Astrocyte cytosolic gcamp6s
%Calcium
            % automated selection
            findConf{1} = ConfigFindROIsFLIKA_2D.from_preset('ca_cyto_astro', 'baselineFrames',...
                BL_frames,'sigmaXY', 2,...
                'sigmaT', 0.5,'threshold_std', 5,...
                'min_rise_time',0.1689, 'max_rise_time', 8,...
                'dilateXY', 4,...
                'dilateT', 0.5,'erodeXY', 2);
            
            
            % Astrocyte Calcium
            % hand selected- cellular structures
            x_pix= Settings.Xres(1,1); y_pix= Settings.Yres(1,1);
            findConf{2} = ConfigFindROIsDummy.from_ImageJ(fullfile(testRoot,'Astrocytes.zip'), x_pix, y_pix,1);
            
            % Neuronal Calcium
            % hand selected
            x_pix= Settings.Xres(1,1); y_pix= Settings.Yres(1,1);
            findConf{3} = ConfigFindROIsDummy.from_ImageJ(fullfile(testRoot,'Neurons.zip'), x_pix, y_pix,1);
            
                        % FLIKA selected
                    findConf{4} = ConfigFindROIsFLIKA_3D.from_preset('ca_neuron', 'baselineFrames',...
                    BL_frames,'freqPassBand',1,'sigmaXY', 2,...
                    'sigmaT', 0.1,'threshold_std', 10, 'threshold2D', 0.2,...
                    'min_rise_time',0.0845, 'max_rise_time', 1,'minPuffArea', 10,...
                    'minPuffTime',0.25,'dilateXY', 2, 'dilateT', 0.3,'erodeXY', 1, 'erodeT', 0.1,...
                    'discardBorderROIs',true);
            %% Configuration for measuring ROIs
            % AWAKE astrocyte cyto calcium
            measureConf{1} = ConfigDetectSigsClsfy('baselineFrames', BL_frames,...'normMethod', 'z-score','zIters', 100,...
                'propagateNaNs', false, 'excludeNaNs', false, 'lpWindowTime', 3, 'spFilterOrder', 2,...
                'spPassBandMin',0.05, 'spPassBandMax', 0.2, 'thresholdSD_low', 3,'thresholdSD_band', 5);
            
            % AWAKE neuron calcium
            measureConf{2} = ConfigDetectSigsClsfy('baselineFrames', BL_frames,... 'normMethod','z-score',... 'zIters', 10000,...
                'propagateNaNs', false,'excludeNaNs', false, 'lpWindowTime', 2, 'spFilterOrder', 2,...
                'spPassBandMin',0.1, 'spPassBandMax', 1, 'thresholdSD_low', 3,'thresholdSD_band', 5);
            
              
            % for calculating AUC for each trace
            detectConf = ConfigMeasureROIsDummy('baselineFrames', BL_frames);
            