

testRawImgs = SCIM_Tif();

configFind = ConfigFindROIsFLIKA.from_preset('AstrocyteMembraneCalcium',...
    'baselineFrames', 10,'sigmaXY', 1,...
    'max_rise_time',7,'minPuffArea',2, 'minPuffTime', 0.4,...
    'dilateXY',2,'threshold_constant', 9);%,...
    %'dilationRadius', 1.0573);
    
    
configFind2 = ConfigFindROIsFLIKA.from_preset('NeuronalCalcium',...
    'baselineFrames', 10,'sigmaXY', 2,...
    'minPuffArea',10,'max_rise_time',0.5,'threshold', 0.2,... 
    'dilateXY',2,'threshold_constant', 10,'erosionRadius',2);

configBoth = ConfigCellScan(configFind2, ConfigMeasureROIsClsfy());

testProcessedImgs5 = CellScan('name', testRawImgs, configBoth);
testProcessedImgs5.process();
testProcessedImgs5.plot_fig();